### ISSUE TITLE
[FR] Long Press instead of double-click

### ISSUE THREAD

**Issue by Baumtreter** [dwainscheeren/lovelace-dwains-theme#101]
I think the title says it - A long press would be better from a UX perspective :)

**Comment by DamianosS** [comment]
To understand that better: I assume, you are referring to the long-press feature of the newer devices, right? That wouldn't work on many existing and cheaper devices that are not providing the prerequisites.
Maybe a configurable option serve both environments?

**Comment by Baumtreter** [comment]
Yes that was my intend. But an option to switch would be the more suitable solution I guess.

**Comment by dwainscheeren** [comment]
I'm not sure if I will make an option for it. I already changed 1 click to toggle and double click to more info popup for all lights in my theme. I think I will do that for all cards/buttons and adding both double click and longpress as option to open more info dialog.

**Comment by flonair** [comment]
> To understand that better: I assume, you are referring to the long-press feature of the newer devices, right? That wouldn't work on many existing and cheaper devices that are not providing the prerequisites.

I think you mean the 3D touch function. It's not the same as a long press. 3D Touch is really only supported by some devices. A long press, on the other hand, should be recognized by nearly all devices with touch.

**Comment by flonair** [comment]
> I'm not sure if I will make an option for it. I already changed 1 click to toggle and double click to more info popup for all lights in my theme. I think I will do that for all cards/buttons and adding both double click and longpress as option to open more info dialog.

Could it be an option that you separate the card?  So click on the icon to switch the light and a click on the name opens the detail popup. Similar to the hue app with the toggle button.

**Comment by dwainscheeren** [comment]
I will make it more consistent in 1.4.0 and configurable option for this would be a lot of work, maybe sometime in the future.
