### ISSUE TITLE
[FR] Updater, with notifications and reloading

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#103]
Do a theme notification when there is a new version, and allow under More, Theme Settings, the ability to see current version and latest version, and click to upgrade and reload

**Comment by dwainscheeren** [comment]
Seeing the current version and the update available version is already built in the current versions. A one click update button would be hard to make, something on the longer term.

**Comment by davidkmcgowan** [comment]
That makes sense, and you can close if you want.  I was thinking like an API you would hit to check if new version, if so, display notification, then you could download it, extract it, and then call the code you already have for reload, somewhat like HACS plugins, this can be in 2.x

**Comment by dwainscheeren** [comment]
I have some things in mind for this, it will come in the future eventually. So lets give it some time :) I will close this for now.
