### ISSUE TITLE
Entity cards just close at times

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#107]
If you go into a room or a device and click to load an entity for details, sometimes they just close on their own, not sure of any pattern or not just yet

**Comment by dwainscheeren** [comment]
Mm strange is this still hapening?

**Comment by davidkmcgowan** [comment]
Yeah, it's random, could be my phone, let me test more on another device, I'm on a Pixel 4, will see if it does it on my wife's Pixel 3

**Comment by dwainscheeren** [comment]
Never heard any other having this issue, also no report back so for now I'm closing this issue :)
