### ISSUE TITLE
[FR] Clicking on switch entity should toggle it

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#108]
Similar to my lock FR, but clicking on a switch by default should just toggle it, you could add to the far right "..." so you could get to entity details still, but default click should just toggle

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0

**Comment by dwainscheeren** [comment]
I will make it more consistent in 1.4.0 and configurable option for this would be a lot of work, maybe sometime in the future.
