### ISSUE TITLE
Missing header navigation bar

### ISSUE THREAD

**Issue by mike391** [dwainscheeren/lovelace-dwains-theme#11]
I am missing the header navigation bar. It appears briefly as I load the page but then disappears as the page finishes loading.

I am running Home Assistant 0.103.0

![image](https://user-images.githubusercontent.com/7278201/74476580-9a98c780-4e77-11ea-87f6-94955d0a2e6a.png)

**Comment by dwainscheeren** [comment]
What do you mean with "missing the header navigation bar"? In the screenshot you posted everything looks all right.

**Comment by mike391** [comment]
I see this for a split second while loading, sorry it took a while to get the screenshot at the right time:

![image](https://user-images.githubusercontent.com/7278201/74477419-45f64c00-4e79-11ea-8911-fb2ac70587c1.png)

Unless this is unintended? I originally assumed it was supposed to look like that because I didnt see any way to access my 'Cameras' after filling out the config for that. I thought maybe the 'Camera' link was supposed to be on that header bar that disappeared.

**Comment by dwainscheeren** [comment]
The view from your first screenshot is how it needs to look like. A bar with only 5 icons nothing else. The second screenshot is the state of the page loading before everything is settled. The cameras are accessible on the 4th tab in the main menu.

**Comment by mike391** [comment]
Just getting a dynamic page on the camera tab though:

![image](https://user-images.githubusercontent.com/7278201/74479743-bbfcb200-4e7d-11ea-960b-3a62379cdc84.png)

**Comment by dwainscheeren** [comment]
Then you didn't followed the documentation. You uncommented the file `dynamic_page.yaml` this will override the camera page. Comment back this file to see your cameras.
