### ISSUE TITLE
If you add temperature and climate to the same room only saw one

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#110]
I added temperature and climate to the same room, not sure why because I had info I needed on climate, but it then showed only the temperature and I couldn't get to my thermostat.  I just removed the temperature from the room and the climate / thermostat device worked fine after that.  The temperature I had was a sensor off the thermostat anyway, but seemed like both entities should have showed up and worked

**Comment by dwainscheeren** [comment]
Temperature is just additional to a room which has a climate. It will override the temperature from the climate.
