### ISSUE TITLE
Center icons

### ISSUE THREAD

**Issue by flonair** [dwainscheeren/lovelace-dwains-theme#117]
Hi dwain,
I found some icons that aren't centered properly. Maybe there are reasons for that, but it is visually very disturbing.
It'd be great if you could adjust this.

Main Page - rooms:
![2020-04-27_12h59_09](https://user-images.githubusercontent.com/60264693/80365622-312a3180-8888-11ea-9f27-9173739d03ac.png)
Main Page - devices:
![2020-04-27_12h58_46](https://user-images.githubusercontent.com/60264693/80365620-30919b00-8888-11ea-9ed5-25677bb7dc21.png)

**Comment by iMartien** [comment]
This probably has to do with the icon files themselves, they are not centered.

**Comment by dwainscheeren** [comment]
This is indeed an problem with the Font Awesome icons it self so cant fix it right now myself.

**Comment by flonair** [comment]
What exactly do you mean? The icons from Font Awesome are perfectly centered. Example: https://fontawesome.com/icons/lightbulb?style=regular

**Comment by dwainscheeren** [comment]
The way they are loaded in HA makes them not centered always.

**Comment by dwainscheeren** [comment]
In 1.4.0 all icons will be centered!
