### ISSUE TITLE
Flexbox Card Not Populating

### ISSUE THREAD

**Issue by bacco007** [dwainscheeren/lovelace-dwains-theme#119]
Note: I'm on 0.109 (which probably makes a difference)

In trying to build some of my 'More Pages' i've been making use of you're great flexbox card however i've noticed that sometimes it doesn't populate, refreshing the browser makes it populate.

I've tried in the latest versions of Chrome, Firefox and Safari

**Comment by dwainscheeren** [comment]
Can you paste me some code how you are ussing the card?

**Comment by bacco007** [comment]
https://github.com/bacco007/HomeAssistantConfig/blob/master/dwains-theme/addons/more_page/netatmo/page.yaml

First Open:
![image](https://user-images.githubusercontent.com/6810572/82765236-4038db00-9e58-11ea-9424-1404b5aa0fa4.png)

After Browser Refresh:
![image](https://user-images.githubusercontent.com/6810572/82765241-4c249d00-9e58-11ea-8e28-2a6d5594e9ac.png)

**Comment by dwainscheeren** [comment]
Not sure, I hope this is fixed in 1.4 because I rewrote the flexbox card, if this still happens in 1.4 then please re-open this issue.
