### ISSUE TITLE
Split room temp/humidity/pressure into different charts

### ISSUE THREAD

**Issue by marcokitzmann** [dwainscheeren/lovelace-dwains-theme#120]
On the detail page for climate control, data for temperature, humidity and air pressure are combined in one single diagram. But because these are completely different measurements, the graphs are only displayed as flat lines that are practically useless. Each of these values should be displayed in a separate chart.
![temp-screen-chart](https://user-images.githubusercontent.com/64691090/80917292-22e38600-8d5e-11ea-996d-a2ce37e8c1d2.png)

**Comment by dwainscheeren** [comment]
From version 1.4 they are in separate graphs.
