### ISSUE TITLE
Temp from weather card in landscape mode, but from local sensor in portrait

### ISSUE THREAD

**Issue by marcokitzmann** [dwainscheeren/lovelace-dwains-theme#121]
In portrait mode the weather card on the start page shows the temperature of my local Netatmo sensor (which I defined in global.yaml). But if I turn the device into landscape mode, the temperature from the weather card is displayed. Is this a bug or a feature?

Anyway: I would like to define all my own weather sensors (besides temperature and humidity also air pressure, wind, rain etc.) in the global.yaml, so that the weather report is generated from my local data where possible. Only where there is no self generated data (e.g. weather forecast), you should use the external weather data.
![weather_temp_landscape](https://user-images.githubusercontent.com/64691090/80917646-ba49d880-8d60-11ea-981d-add99d5084f7.png)
![weather_temp_portrait](https://user-images.githubusercontent.com/64691090/80917647-bae26f00-8d60-11ea-8de0-a91212d4e0ce.png)

**Comment by dwainscheeren** [comment]
Will take a look into this asap.

**Comment by dwainscheeren** [comment]
The weather temp bug difference between desktop/mobile is fixed in 1.4. For other weather data I need to look in the future, Can you please make a new FR for this?
