### ISSUE TITLE
Light status don't updated

### ISSUE THREAD

**Issue by sdomotica** [dwainscheeren/lovelace-dwains-theme#122]
I'm running HA 0.109.3 in Hassio and your addon 1.3.1
All the hacs plugin up to date.
When I update light, the GUI don't receive update. I have to refresh browser.
The lights are Lifix. No problem with normal MQTT light with only on/off
This the video

[darwn.zip](https://github.com/dwainscheeren/lovelace-dwains-theme/files/4580092/darwn.zip)

Bye
Sandro

**Comment by dwainscheeren** [comment]
What happens if you go to these lights in the configuration of HA self and turn them on/off there?

**Comment by dwainscheeren** [comment]
I think it's sorted out? Never heard anyone else with this issue so it seems its related to your main HA setup and not the theme, please re-open this issue if problem still exists.
