### ISSUE TITLE
invalid key: "OrderedDict([("_d_t_icons.room_header_more_entities|default('mdi:arrange-bring-forward')", None)])" in "/config/dwains-theme/plugins/button-cards-templates/rooms/header/more_entities.yaml", line 5, column 0

### ISSUE THREAD

**Issue by xianweitudou** [dwainscheeren/lovelace-dwains-theme#124]
I like the theme 'HKI' of jimz011, and I also love your 'dwains-theme', but when I configure it in the same HA, lovelace always prompts the issue of 'single quotes' and 'double quotes' when refreshed, I am Chinese environment, I want to know is because of the language environment problem? Or what I missed, thank you very much. I want to know the Probably  reason，language environment? I don't know what I missed, I read your documents carefully, look forward to your reply, thanks again to bring us such a good look interface themes

**Comment by dwainscheeren** [comment]
At this moment you can't run/have HKI and Dwains Theme installed and running on the same HA installation.

**Comment by xianweitudou** [comment]
> At this moment you can't run/have HKI and Dwains Theme installed and running on the same HA installation.

thank you very much，and  best wishes for you.
