### ISSUE TITLE
HA Multiple Lovelace Dashboard setup

### ISSUE THREAD

**Issue by auredor** [dwainscheeren/lovelace-dwains-theme#127]
I was looking to configure several dashboard through Lovelace Dashboard setup page. 

I've succeeded to get Dwains theme and some other lovelace dashboards (UI managed).

However, I'm not able to remove Dwains Theme shortcut in the left panel for a UI managed dashboard.

Also, when I try to add ressources through the HA Ressources editor, I get this message : 
"You're using Lovelace in YAML mode. So, you cannot manage ressources through the user interface."

This is quite unexpected as I try to ad ressources from the UI managed dashboard for the UI managed dashboard. So nothing related to Dwains Theme and so YAML mode ??? The only way is to add the new ressources to configuration. yaml !
 
I guess this is related to dwains theme taking over the configuration for the front-end. But still, it prevents the user to manage ressources the way it should be.

Thank you.

**Comment by dwainscheeren** [comment]
A custom theme requires the lovelace mode set to YAML. You need to add your custom resources to `dwains-theme/resources/custom_resources.yaml`. It's the way HA works so it's not really related to Dwains Theme.

**Comment by auredor** [comment]
Hello.

I don't have all the clues of how HA dashboard works but my understanding
is that for Dwain Theme Dahsboard, additional ressources must be added to
dwains-theme/resources/custom_resources.yaml.
However, *within other dashboard managed through UI* (standard lovelace
card), the additionnal ressources (requested to be added by whatever
integration from HACS) might be added to configuration.yaml or with
Lovelace in storage mode.  In this last case, I get the unexpected message.
I suspect this unexpected behavior is caused by Dwain Theme as I didn't get
this issue before its installation.

Thank you

Le mar. 26 mai 2020 à 11:40, Dwain Scheeren <notifications@github.com> a
écrit :

**Comment by dwainscheeren** [comment]
Got it sorted?

**Comment by auredor** [comment]
No, sorry.

My only workaround is to use configuration.yaml for the
additional ressources (no dwains theme related). But, since dwains theme
installation, I cannot add them with Lovelace in storage mode.

Regards,

Le lun. 1 juin 2020 à 10:09, Dwain Scheeren <notifications@github.com> a
écrit :

**Comment by dwainscheeren** [comment]
You need to add them to `dwains-theme/resources/custom_resources.yaml`
