### ISSUE TITLE
Theme is loading extremely slowly on 0.110.4

### ISSUE THREAD

**Issue by chansters** [dwainscheeren/lovelace-dwains-theme#129]
The theme has been working great for a while.  I just upgraded to 0.110.4 today and the theme is now loading very slowly.  But that I mean, each of the room buttons on the home screen is taking a long time before they appear.

**Comment by Klumpke** [comment]
This is a known issue and is fixed in the upcoming release (1.4.0). At this moment the theme is not compatible with Home Assistant 0.110.x

**Comment by dwainscheeren** [comment]
This will be fixed in the up coming version 1.4 of Dwains Theme.
