### ISSUE TITLE
[BUG] media player more info not working

### ISSUE THREAD

**Issue by tuepen** [dwainscheeren/lovelace-dwains-theme#13]
when i try more info on media player nothing comes up.

what would i be missing?

**Comment by dwainscheeren** [comment]
What sort of entity is it. Can you go to Developer Tools and show the attributes of it?

**Comment by tuepen** [comment]
Its just the icon for the rooms addon page

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dwainscheeren** [comment]
Mmm it needs to work. Can you join slack to debug it together?

**Comment by tuepen** [comment]
sorry the media player entity is working now.. i updated all my HACS add ons
