### ISSUE TITLE
Cover Slider not working

### ISSUE THREAD

**Issue by Nasserish** [dwainscheeren/lovelace-dwains-theme#147]
I am using a cover template to control the curtains using RF. After updating to 1.4 the cover changed to slider button instead of up and down cover button, and it does not work. When I turn down the cover from developers' tools the status is updated on the theme.

Thanks

**Comment by Xetoxyc** [comment]
Interesting, seems like your Cover cannot be set by position but has the feature flag enabled. Which control unit are you using ?

**Comment by Nasserish** [comment]
I am using Broadling RM Pro to control generic roller blinds.

Cover configuration:
`  - platform: template
    covers:
      study_shades:
        friendly_name: "Study blinds"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.roller_blindes_study
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.roller_blindes_study
        stop_cover:
          service: switch.toggle
          data:
            entity_id: switch.roller_blindes_study
        icon_template: >-
          {% if is_state('switch.roller_blindes_study', 'on') %}
            mdi:window-open
          {% elif is_state('switch.roller_blindes_study', 'off') %}
            mdi:window-closed
          {% else %}
            mdi:window-closed
          {% endif %}`

HA default view
![image](https://user-images.githubusercontent.com/34910483/85018019-22b81200-b175-11ea-845b-646274da42c3.png)

**Comment by Xetoxyc** [comment]
Please try to add [value_template](https://www.home-assistant.io/integrations/cover.template/)
 to your configuration. Maybe this will change the supported features to up/down/stop only

Its interesting that that your default view does not look like that
![image](https://user-images.githubusercontent.com/7449973/85018834-1da39480-b16e-11ea-805e-e85c7a6a815e.png)

You could also check what are the real supported_features flags of your cover by puting an breakpoint there.
![image](https://user-images.githubusercontent.com/7449973/85019075-7f63fe80-b16e-11ea-8091-548b9be74959.png)

Would be great if you could tell me the int-value which is set there.

**Comment by Xetoxyc** [comment]
I just checked the HA-Code

https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py Ln 215

It would be awesome if you could check whats happening there and what's the real self.current_cover_position value

**Comment by Nasserish** [comment]
I've just added value template but that doesn't seem to change anything. I'm not sure if my configuration is correct though 

`  - platform: template
    covers:
      study_shades:
        friendly_name: "Study blinds"
        value_template: "{{ states('cover.study_shade') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.roller_blindes_study
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.roller_blindes_study
        stop_cover:
          service: switch.toggle
          data:
            entity_id: switch.roller_blindes_study
        icon_template: >-
          {% if is_state('switch.roller_blindes_study', 'on') %}
            mdi:window-open
          {% elif is_state('switch.roller_blindes_study', 'off') %}
            mdi:window-closed
          {% else %}
            mdi:window-closed
          {% endif %}`

**Comment by Xetoxyc** [comment]
> I've just added value template but that doesn't seem to change anything. I'm not sure if my configuration is correct though
> 
> ` - platform: template covers: study_shades: friendly_name: "Study blinds" value_template: "{{ states('cover.study_shade') }}" open_cover: service: switch.turn_on data: entity_id: switch.roller_blindes_study close_cover: service: switch.turn_off data: entity_id: switch.roller_blindes_study stop_cover: service: switch.toggle data: entity_id: switch.roller_blindes_study icon_template: >- {% if is_state('switch.roller_blindes_study', 'on') %} mdi:window-open {% elif is_state('switch.roller_blindes_study', 'off') %} mdi:window-closed {% else %} mdi:window-closed {% endif %}`

Nahh was my error couldnt change anything as the code does not change anthing related to your problem

**Comment by Nasserish** [comment]
> this lines are activiating position feature. Would be great if you can check the values in 211 becuase it seems like position_action is not None

I'm not sure what do you mean ? 🙈

**Comment by Xetoxyc** [comment]
:D that goes pretty deep. Nevermind.

Could you try 

set_cover_position: None

as additional setting. Maybe forcing None does work.

**Comment by Nasserish** [comment]
`nvalid config for [cover.template]: expected dictionary @ data['covers']['study_shades']['set_cover_position'][0]. Got 'N'. (See ?, line ?). 
`
I get this error.

I am thinking to change the lines in cover-card.js to: (a shot in the dark )

`render() {
  
  var entity = this.config.entity;
  var stateObj = this.hass.states[entity];

  const name = stateObj.attributes.friendly_name === undefined
          ? stateObj.entity_id.split(".")[1].replace(/_/g, " ")
          : stateObj.attributes.friendly_name;
    return html`
      <ha-card
          .header=${this.config.title || name}>
          <div class="buttons">
            <ha-cover-controls
                .hass="${this.hass}"
                .stateObj="${stateObj}"
            ></ha-cover-controls>
          </div>
      </ha-card>
    `;
  }
}
`

**Comment by Xetoxyc** [comment]
try `:null` instead. Sorry but this are just tries to fix it. I have no time to reproduce every step currently :(

**Comment by Nasserish** [comment]
> ` I am thinking to change the lines in cover-card.js to: (a shot in the dark ) `
I deleted the file and that didn't make a difference 🤣 

Now in can see a position value, but still can't control the cover
![image](https://user-images.githubusercontent.com/34910483/85027955-2f436700-b183-11ea-82a2-5b65108fbd7e.png)

**Comment by Xetoxyc** [comment]
I checked lovelace cover card generator and it uses supported feature also. Pretty strange things are broken for you.

**Comment by Nasserish** [comment]
For anyone having the same problem. I used the custom component below and it works now:
[https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based](url)

Thanks @Xetoxyc
