### ISSUE TITLE
Unavailable Lights/Switches displayed as "on"

### ISSUE THREAD

**Issue by mattz** [dwainscheeren/lovelace-dwains-theme#148]
Hi, I am using version 1.4.0 and have found if a switch/light is unavailable, they display in the UI as On.

eg:
![image](https://user-images.githubusercontent.com/221673/84963027-a0672800-b14b-11ea-8469-ae3a1d885a31.png)

![image](https://user-images.githubusercontent.com/221673/84963051-b1b03480-b14b-11ea-83e2-5ab8e536b5e6.png)

**Comment by dwainscheeren** [comment]
This will be fixed in 1.4.1 :)
