### ISSUE TITLE
Cannot access the iframe panel from phone

### ISSUE THREAD

**Issue by mwbehr1** [dwainscheeren/lovelace-dwains-theme#15]
I cannot seem to access the left iframe panel from my phone. I recognize that you have included links directly to Configuration and Developer Tools, but there are many more items on that pane that I would like to access.

The pane is available from my desktop browser, just for clarification.

**Comment by dwainscheeren** [comment]
This will be fixed in 1.1.2. You then can access the sidemenu on mobile by going to More -> House data. On that page the sidebar will work, its also the only page it will work then.
