### ISSUE TITLE
Room temperature page card size mismatch

### ISSUE THREAD

**Issue by jakezp** [dwainscheeren/lovelace-dwains-theme#160]
When added `temperature:` and `humidity:` to a room config without adding `climate:`, the temperature and humidity cards sizes do not match.

Room config:
```
  - name: Bedroom 1
    icon: mdi:bed-single
    temperature: sensor.bedroom1_temp
    humidity: sensor.bedroom1_humidity
```

This is not a problem if `climate: ` is also configured, because these cards are not displayed, but rather the thermostat card is being displayed.

<img width="1416" alt="Screenshot 2020-06-30 at 23 00 28" src="https://user-images.githubusercontent.com/6917873/86177340-be0e9700-bb26-11ea-9402-9027b7e4063f.png">

**Comment by dwainscheeren** [comment]
Fixed in 1.4.1
