### ISSUE TITLE
Error when reloading theme configuration in theme settings

### ISSUE THREAD

**Issue by lundig** [dwainscheeren/lovelace-dwains-theme#166]
Logger: homeassistant.components.websocket_api.http.connection.2910274128
Source: custom_components/dwains_theme/__init__.py:324
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:51:32 (1 occurrences)
Last logged: 23:51:32

can only concatenate str (not "bool") to str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/dwains_theme/__init__.py", line 324, in handle_reload
    translations = load_yaml(hass.config.path("dwains-theme/translations/"+language+".yaml"))
TypeError: can only concatenate str (not "bool") to str
Kunne ikke tilkalle tjenesten: dwains_theme/reload can only concatenate str (not "bool") to str

**Comment by dwainscheeren** [comment]
I think you have a mistake in your config, can you share some more information about the dwains theme config files?

**Comment by lundig** [comment]
When i change lanuage to "EN" the reload function works.

**Comment by dwainscheeren** [comment]
Which language did you try to use then? Is it in the available translations?

**Comment by cskogstrand** [comment]
@dwainscheeren I found the problem. In the norwegian translation file it starts with "no:" this is somehow interpreted as a datatype and not the string "no". Changing it to "nor:" and the filename to nor.yaml fixed it for me :)

**Comment by stabasm** [comment]
Hello!
There still seems to be an issue with norwegian language files. But if you change the lang.code for norwegian from no to nb (Norwegian Bokmaal) the issue is resolved. 
Change "Norwegian" : "no", in process_yaml.py to "Norwegian" : nb,, rename the languagefile from no.yaml to nb.yaml and change the language code from "no":  to "nb":  in nb.yaml.

**Comment by dwainscheeren** [comment]
Maybe an issue with the word 'no' ?

**Comment by stabasm** [comment]
> Maybe an issue with the word 'no' ?

Yes, I agree, That's why I propose replacing the word no with nb (abbreviation for Norwegian Bokmaal). Shall I just upload a languagefile named nb.yaml to your github repository or shall we just edit/rename the existing one?
