### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by groft389** [dwainscheeren/lovelace-dwains-theme#168]
Hey,

Just a small thing ^^ 
There is missing a space between "Offen" and the number of open doors :)
![Screenshot_4](https://user-images.githubusercontent.com/17033125/86815642-2d363f00-c083-11ea-86be-3b660cc604b5.png)
(Is in a room Overview)

**Comment by dwainscheeren** [comment]
Fixed in 1.4.1.
