### ISSUE TITLE
[FR] Add Binary sensors in room headers.

### ISSUE THREAD

**Issue by AalianKhan** [dwainscheeren/lovelace-dwains-theme#169]
Hello, I have some moisture and sound sensors around my home and I would like to add them to his theme. However, there is no s good implementation of this as far as I can find. devices are an option but it ignores device class and says on/off instead of wet/dry and etc.  I would love to be able to add my own binary sensors on the header of my room beside door status and motion. this does raise the question that the header can be cluttered really fast so removing titles and only seeing icons would be good enough for me. I love this theme and has real good potential.

**Comment by AalianKhan** [comment]
I have found that using "page entities" does a good job for doing this, but if there are no other entities/groups like media players, lights or devices, then "page entities" does not show up. I have one room that only has a water sensor and I am unable to view it.

**Comment by patman15** [comment]
@AalianKhan you might want to have a look at #156. Probably the work around I posted is of help for you. I'm still not sure why there are two separate cards for standard entities and additional page_entities, otherwise I might be able to fix it with a pull request.

**Comment by AalianKhan** [comment]
thanks that fixed the problem. I guess if you want to hide some entities to clean the room page but still want to be able to control the entity then you can use more entities. Otherwise, if you want it to be easily accessible without many clicks then use page entities.
