### ISSUE TITLE
Can room addons have icon templates please 

### ISSUE THREAD

**Issue by tuepen** [dwainscheeren/lovelace-dwains-theme#17]
I have a room with multiple device... eg Laundry with washing machine and dryer.
I have grouped them, but it doesnt easily show me their status
I have created an addon room for washing machine and one for dryer, and I would like to be able to have the icon for those addons change based on whether the machine is on or off.

**Comment by dwainscheeren** [comment]
If you add them to a group of devices you can see the status there. My machines return on/off so I can see if they are running or not. You can use ui-customize to set icons on off/on states but I don't give any support on this.

**Comment by tuepen** [comment]
so in the ui-customise i should be able to template the icon for the room addon?

**Comment by tuepen** [comment]
this is what i want to do (the commented bit) but it isnt supported

     addons:
      - name: Washing Machine
        icon: mdi:washing-machine
#        icon_template: >-
#          {% if is_state('input_boolean.washing_machine_switch', 'true') %}
#          mdi:washing-machine
#          {% else %}
#          mdi:washing-machine-off
#          {% endif %}
        path: 'dwains-theme/addons/rooms/laundry/page.yaml'
        data:
          machine: washing_machine
          machine_name: Washing Machine
      - name: Dryer
        icon: mdi:tumble-dryer
#        icon_template: >-
#          {% if is_state('input_boolean.dryer_switch', 'true') %}
#          mdi:tumble-dryer
#          {% else %}
#          mdi:tumble-dryer-off
#          {% endif %}
        path: 'dwains-theme/addons/rooms/laundry/page.yaml'
        data:
          machine: dryer
          machine_name: Dryer

**Comment by dwainscheeren** [comment]
You can't use jinja in those config files. Regarding custom ui I mean this: https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md There you can set 2 icons on state of an entity by using the `customize.yaml` file in HA itself, my theme then loads those icons in on the devices page.

If you want to keep your existing room addon you need to parse those on and off icons with the data attribute to the addon and handle it inside the `page.yaml`

**Comment by tuepen** [comment]
ok thanks, so it looks like i cant do it on the room addon item, as it is not an entity.
