### ISSUE TITLE
Cover (garage door) with only open/close capabilities not showing correctly on the cover card.

### ISSUE THREAD

**Issue by thewazz1** [dwainscheeren/lovelace-dwains-theme#170]
Looking at the javascript for the Dwains-cover-card.js, it looks like there is a different display for covers that only have open/close versus open/close/tilt.  My garage doors only have open/close, but it is showing the display with the open % and when the garage door is open it is showing undefined for the state, and not switching over to the simplified view of just open or closed.  Looking at line 32 of Dwains-cover-card.js, if(stateObj.attributes.supported_features & 7 > 0) it looks like this will always evaluate to true (I don't know javascript, but I think I can read this), since 7 is always greater than 0.  I think this logic needs to be modified to something like this maybe: if(stateObj.attributes.supported_features > 7)

**Comment by Xetoxyc** [comment]
supported_feature & 7 > 0

Means there is an and bitoperation of the value of supported feature and 7.
Which means the value of the result is only greater than zero if the first 3 bits are set.

**Comment by thewazz1** [comment]
Hmm, ok... well I have a MyQ, and if I look in Developer Tools it has supported_features of 3.  So only the first two bits are set.  However, it is showing the two covers as if they have tilt indicators on them, instead of just the up and down arrow.

**Comment by Xetoxyc** [comment]
I will fiy this and create a specified pull request for this today afternoon

**Comment by thewazz1** [comment]
Great, thank you!

**Comment by Xetoxyc** [comment]
I just pushed a pull request fixing this
You can use mentioned pull request within your project until dwain accepted the pull request.

Seems like you should not answer and code when you are tired 😂 I don't know what I thought when I coded this bitwise operation.

**Comment by AalianKhan** [comment]
Great, I had the same problem. Thank you

**Comment by thewazz1** [comment]
Thanks for updating this code.  However, for whatever reason, it is still trying to show me the version of the card that has support for tilt and position.  I went into Chrome's developer tools and confirmed that it was pulling the new javascript.  I also put a breakpoint into the Dwains-cover-card and confirmed that the supported_features attribute is passing the number 3, but if I step the code it goes into the first True block, for support of tilt and position.  Which doesn't make since because 3 would not match up to 4 or 128.

**Comment by boutch** [comment]
I am having exactly the same issue. For me supported_features is 11 and it does not support the % or title so I can't control my covers at all using the dwains theme. The previous buttons up, down, stop were working fine. I also checked and I am running the latest code.

**Comment by Xetoxyc** [comment]
It is a caching problem for sure. I just added a new version tag to the file and modified the loaded file to v4. This should solve your problem. Don't hesitate if it is still not working for you.

**Comment by thewazz1** [comment]
I pulled down the updated code and replaced it.  Cleared cache, rebooted HA, and still trying to show me tilt, etc.  Verified in Chrome's Dev tools that it is pulling 0.0.4 version.

**Comment by thewazz1** [comment]
I was playing around with the javascript and changed the conditions in the if/else if/else to get rid of the bitwise and, and replaced with just regular greater than and it worked.  So if changed to: if(stateObj.attributes.supported_features >16 ), the else if to: else if(stateObj.attributes.supported_features > 3).  Changed supported_features in HA Developer Tools to various values and appeared to work, as it changed the way that garage door showed.  Don't know if this is valid logic.

**Comment by Xetoxyc** [comment]
*Facepalm*... some brackets to the right place and everything is working fine .
https://en.wikipedia.org/wiki/Order_of_operations

**Comment by thewazz1** [comment]
That did the trick! Thanks!
