### ISSUE TITLE
[FR] Show windows open

### ISSUE THREAD

**Issue by lewisurwin** [dwainscheeren/lovelace-dwains-theme#175]
Would be great to replicate the lights on button on the homepage for windows or doors open so can easily check when leaving the house.

**Comment by dwainscheeren** [comment]
Not sure what you mean. Can you explain it more clearly to me? :)

**Comment by lewisurwin** [comment]
![Screenshot_20200724-094447](https://user-images.githubusercontent.com/56207153/88374848-6adcdc80-cd92-11ea-8805-1e0dffee9713.png)

At the top where it shows any lights on, it would be great if it could also show any binary_sensors that are currently open with class 'window'.

This would show very quickly whether there are any windows when going to bed, or about to leave the house for example.

Thanks so much for all your work on the theme, it looks amazing!

**Comment by dwainscheeren** [comment]
This is al ready possible? You can add windows to a room and if that window is open it shows in the top.

**Comment by lewisurwin** [comment]
I'm saying more about the homepage, unless I'm missing something. Aware of the per room view but would love to have it shown for the whole house

**Comment by Klumpke** [comment]
That is already there.
![20-07-24 20-39-19 6596](https://user-images.githubusercontent.com/9717529/88424513-f20b6e00-cded-11ea-8bc3-f82e6d1e9496.png)

**Comment by lewisurwin** [comment]
Ah, mine only shows lights.
Am I missing something somewhere? Can't see any mention in the documentation

**Comment by dwainscheeren** [comment]
See: https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html#rooms-information and then for example covers or windows

**Comment by lewisurwin** [comment]
Found the error! Miss-pelled the window group in config. Oops!
