### ISSUE TITLE
Add switch domain to rooms - feature request

### ISSUE THREAD

**Issue by MikeTheCleric** [dwainscheeren/lovelace-dwains-theme#178]
Hi, I've got a request. 
Can you add the switch domain in room cards? I think that this domain is necessary to Dwains because it's a common domain in Home Assistant.

Thanks in advice!

**Comment by dwainscheeren** [comment]
Hi, not sure what you mean with this but you can add a switch as a light in the lights of a room or underneath the devices.

**Comment by MikeTheCleric** [comment]
Thanks!
