### ISSUE TITLE
Custom element doesn't exist: mod-card.

### ISSUE THREAD

**Issue by tomiruhno1** [dwainscheeren/lovelace-dwains-theme#198]
i get error: Custom element doesn't exist: mod-card.
why is that so?
Did every single step that there was, reinstalled it, i placed card mod folder to evrywhere but it still cant find it. Restared the HA few times.

**Comment by dwainscheeren** [comment]
Did you cleared your browser cache?

**Comment by dwainscheeren** [comment]
No response, since this error is not reported by other users. I gona close it

**Comment by NVader2000** [comment]
Started from nothing again and got the Dwains Theme on the left pane showing up. However, I am getting the following error when I select the Dwains Theme.

Custom element doesn't exist: mod-card.

Please advise
