### ISSUE TITLE
Increase the padding under the person badges

### ISSUE THREAD

**Issue by Brausmith** [dwainscheeren/lovelace-dwains-theme#2]
This is a visual enhancement. I would like to see a little more padding under the person badges. Maybe by the same spacing as between the House Info badge and the person badge.
![ha_dt_spacing](https://user-images.githubusercontent.com/3722950/74298906-30145880-4d9f-11ea-9b9a-4f4c330d6240.png)

**Comment by dwainscheeren** [comment]
I did this because on mobile your homepage with rooms has some more height (because the header is smaller). I will add back some padding if you prefer (and other people) prefer this.

**Comment by dwainscheeren** [comment]
This will be fixed in 1.1.2
