### ISSUE TITLE
[FR] Ability to add input_select devices to existing pages

### ISSUE THREAD

**Issue by mwbehr1** [dwainscheeren/lovelace-dwains-theme#21]
I understand we could add a dynamic or addon page, but was wondering if it would be reasonable to add in input_select option to one of the existing pages. I was personally thinking the Scenes page since I don't really use that one for much right now anyway.

**Comment by dwainscheeren** [comment]
I'm not sure why anyone would like to use an input_select. But I can inform you that of version 1.1.2 its possible to use switch or input_boolean as an scene entity in the `scenes.yaml` file. This way you can make some scenes automations. So toggle an input_boolean on, active an automation and do some things.

![scenes112](https://user-images.githubusercontent.com/3868853/74586843-e5d3e700-4feb-11ea-95c0-1d25104a621b.png)

**Comment by mwbehr1** [comment]
Thank you for the reply. My particular use probably comes from my experience with the SmartThings platform. I had created a single input_select for all of the "home states" of my home. That way only one can be selected at a time, and I didn't need clunky automations to turn the others off when one is selected.

**Comment by dwainscheeren** [comment]
I'm looking into this for you.

**Comment by dwainscheeren** [comment]
Next version will support this.
