### ISSUE TITLE
Error "Custom element doesn't exist: drains-collaps-card" after upgrade from 1.3.1 to 1.4.1

### ISSUE THREAD

**Issue by stebdus** [dwainscheeren/lovelace-dwains-theme#210]
Hi folks,

after I upgraded Dwains-Theme following the official description from 1.3.1 to 1.4.1 I receive the error "Custom element doesn't exist: drains-collaps-card" on the Dwains Theme "Homepage". The other entities are working well.

Any advice.

Cheers
Stefan

**Comment by stebdus** [comment]
Strange enough. The error disappeared this morning after I refreshed the browser and deleted the cache.

**Comment by dwainscheeren** [comment]
Glad to hear that. Always clear your browser cache after an update.
