### ISSUE TITLE
CH will break in next release

### ISSUE THREAD

**Issue by Tosko4** [dwainscheeren/lovelace-dwains-theme#211]
Custom Header (CH) will no longer be maintained and will break with next HA release. As this lovely theme is using CH, can we consider some redesign for 1.5 release maybe? @dwainscheeren 

https://community.home-assistant.io/t/custom-header/155399/1102

**Comment by dwainscheeren** [comment]
See: https://community.home-assistant.io/t/dwains-theme-auto-generating-lovelace-theme-for-dekstop-tablet-and-mobile-v1-4-1/168593/1026?u=dwains and https://community.home-assistant.io/t/dwains-theme-auto-generating-lovelace-theme-for-dekstop-tablet-and-mobile-v1-4-1/168593/1036?u=dwains
