### ISSUE TITLE
[FR] Garage Door Integration

### ISSUE THREAD

**Issue by weaverprojects** [dwainscheeren/lovelace-dwains-theme#22]
I would love to see a integration with the device class garagedoor. My cover.garage_door entity is shown as a blind and doesn't work properly. 

this is the code from the configuration.yaml for the cover entity:

`cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garage"
        value_template: "{{ is_state('binary_sensor.garagentor', 'on') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagentor
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.garagentor
        stop_cover:
          service: switch.turn_on
          data:
            entity_id: switch.garagentor
        icon_template: >-
          {% if is_state('cover.garage_door', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}`

this ist the code from the rooms.yaml:

`- name: Garage
    icon: fas:warehouse
    cover: cover.garage_door 
    media_player: media_player.garage`

and pictures from the frontend:

<img width="488" alt="Bildschirmfoto 2020-02-15 um 07 36 41" src="https://user-images.githubusercontent.com/26321173/74583307-1143db00-4fc6-11ea-8413-c64f1a115b92.png">
<img width="488" alt="Bildschirmfoto 2020-02-15 um 07 36 53" src="https://user-images.githubusercontent.com/26321173/74583310-14d76200-4fc6-11ea-8424-85183154dc47.png">

**Comment by dwainscheeren** [comment]
Maybe its better to make an own part in rooms for garage_doors so not have them inside cover(group) What do you think?

**Comment by weaverprojects** [comment]
You mean the switch and the door Sensor in a room and Not the cover entity?

**Comment by dwainscheeren** [comment]
Can you post the entity attributes of this entity from developer tools -> states? Then I can look how to implement this. Thanks.

**Comment by weaverprojects** [comment]
<img width="488" alt="Bildschirmfoto 2020-02-15 um 16 23 18" src="https://user-images.githubusercontent.com/26321173/74590581-f72eea80-500f-11ea-8cce-6c5757bdc19a.png">

<img width="488" alt="Bildschirmfoto 2020-02-15 um 16 23 34" src="https://user-images.githubusercontent.com/26321173/74590582-fb5b0800-500f-11ea-8564-66dd75e9e5a1.png">

<img width="488" alt="Bildschirmfoto 2020-02-15 um 16 23 58" src="https://user-images.githubusercontent.com/26321173/74590584-fdbd6200-500f-11ea-9474-32c081deb302.png">

<img width="488" alt="Bildschirmfoto 2020-02-15 um 16 25 22" src="https://user-images.githubusercontent.com/26321173/74590585-ff872580-500f-11ea-870f-1bfa7c720f0d.png">

Thats all... I need only a switch to open and close the Garagedoor.

**Comment by dwainscheeren** [comment]
What happens when you put `cover.garage_door` inside room covers?

**Comment by weaverprojects** [comment]
That's what I described in the first Post.

**Comment by dwainscheeren** [comment]
Does those buttons work then up and down?

**Comment by weaverprojects** [comment]
Yes they work. But it looks horrible and the Buttons are a little bit tiny as you see in the pictures.

**Comment by weaverprojects** [comment]
I thought there could only be a switch

**Comment by dwainscheeren** [comment]
Did you try latest version if it looks better?

**Comment by dwainscheeren** [comment]
@weaverprojects Already looked into it?

**Comment by weaverprojects** [comment]
Yes. it works so far. But it shows an undefined% when the garage door is open. A Garage Door Integration with icon, state etc. would be fine.

I'm using a switch and the door integration at the moment.

<img width="488" alt="Bildschirmfoto 2020-02-28 um 06 43 49" src="https://user-images.githubusercontent.com/26321173/75513640-b5ca1200-59f5-11ea-9936-8e0ce14b534c.png">

**Comment by jaburges** [comment]
can i add the garage door also has the open to have the following states:
'Opened`
`Opening`
`Closed`
`Closing`

**Comment by dwainscheeren** [comment]
Does your entity send this @jaburges ?
