### ISSUE TITLE
[FR] Option to unwrap group of devices on room page

### ISSUE THREAD

**Issue by haplm** [dwainscheeren/lovelace-dwains-theme#23]
It would be nice if there would be an option to display group of additional devices for a room "unwrapped" directly on the room main page, without having to tap on "Devices". The thing is all sensors but one

**Comment by dwainscheeren** [comment]
How do you mean with ?

> The thing is all sensors but one

**Comment by haplm** [comment]
Sorry, for some reason the end of the sentence is cut out. I wanted to say that all sensors in my room but one fall into the "Devices" group, which doesn't look nice. Like this:

<img width="566" alt="Screenshot 2020-02-16 at 16 32 22" src="https://user-images.githubusercontent.com/295448/74607543-f6fb2180-50d9-11ea-8231-7fc8e0cd166e.png">

<img width="531" alt="Screenshot 2020-02-16 at 16 32 30" src="https://user-images.githubusercontent.com/295448/74607547-fa8ea880-50d9-11ea-800d-1404afddd5fc.png">

**Comment by dwainscheeren** [comment]
What are those 4 devices in English there?

**Comment by haplm** [comment]
It is a Fibaro smart plug (https://www.fibaro.com/en/products/wall-plug/), smoke sensor (https://www.fibaro.com/en/products/smoke-sensor/) which exposes 2 devices, and flood sensor (https://www.fibaro.com/en/products/flood-sensor/)

**Comment by Brausmith** [comment]
I agree with this. I have in my Laundry a Washing Machine and a Dryer and would like to see them directly in the room, not the group.
In the yaml it would be convenient to list multiple device entities, rather than using a group.

**Comment by dwainscheeren** [comment]
You can use now `more_entities` for a room it adds some extra entities inside a popup which can be access at top right of a room page.

**Comment by haplm** [comment]
While it works (thanks), it kinds goes contrary to what I have meant by this issue ;-). I wanted to see additional entities directly on the room page. This makes them even less visible than using the group additional devices. Is there a reason why are you trying to burry these devices so they are not easily visible? It would be nice to see that CO detector is not (or is) triggered without having to tap to the popup icon....

**Comment by dwainscheeren** [comment]
What if the `more_enties` which are now on that new page inside a room can be directly visible on the bottom of the room page? Would that fill your needs?

**Comment by haplm** [comment]
Yes, that sounds like a solution...

**Comment by Brausmith** [comment]
I've just upgraded to v1.2.0 and have seen the new more_entities feature.
Yes, I would prefer these devices to be listed at the bottom of the room for the more commonly accessed devices.
But, I do feel the current more_entities feature is good for lesser accessed devices. So is there a place for having both functionality?

**Comment by dwainscheeren** [comment]
Need to look into that, my plan was to add a function to more_entities where you can set a option like mode: popup/page itself

**Comment by dwainscheeren** [comment]
Okay so I think I made something for you.
```    
  more_entities:
      popup:
        - entity: sensor.steps
        - entity: sensor.steps
      page:
        - entity: sensor.steps```

**Comment by Brausmith** [comment]
Yes, that's looking more suitable. Two comments:
1. Can the More Entities be full width like the others, so they show the full name?
2. Does it even need to show the "More Entities" label? In a room which has no standard devices like lights, thermostat, media, etc, labelling it as 'more' doesn't seem right.

**Comment by dwainscheeren** [comment]
1. I can make an option for it if you like :) so you have rows of 1 or 2 cards
2. I can make that if there are no room buttons above it that it hides that text otherwise It will be showed because it can be confusing for people, because they look the same as the main buttons.

**Comment by dwainscheeren** [comment]
Please check version 1.2.1

**Comment by haplm** [comment]
Thanks, it is almost perfect, but it only works on my phone. Computer or tablet shows this:
<img width="1259" alt="Screenshot 2020-02-29 at 18 33 42" src="https://user-images.githubusercontent.com/295448/75612265-384ff000-5b22-11ea-95d2-47498dcc363b.png">

When I make the browser window really narrow, it gets fixed.

**Comment by dwainscheeren** [comment]
Ah yes this are some preparations for the tablet/desktop optimization, forgot to comment them out I see. Nah I hope it wouldn't be a big of problem for you. It will be fixed in next version.

**Comment by haplm** [comment]
Yeah, no problem, I'm still configuring things, so I don't need the dashboard for next couple of days...
