### ISSUE TITLE
Additional Lovelace cards

### ISSUE THREAD

**Issue by joyka** [dwainscheeren/lovelace-dwains-theme#24]
I'm using custom card to show Zigbee2MQTT network map (https://github.com/azuwis/zigbee2mqtt-networkmap) in my setup. And I have to add it to the resources section of ui-lovelace.yaml each time theme is updated. Would be nice to have an option to keep separate somehow, so updates would be less painful.

**Comment by dwainscheeren** [comment]
The `ui-lovelace.yaml` file is the only one with some update problems indeed. I cant split up the required part and the own user part in 2 include files. Maybe I remove it from the update process to override this file, only when there is a update with some changes in it, but till now that has been not the case.

Requiring your zigbee2mqtt network map. Are you ussing hassio? It has a addon for this. I use this myself and then you have a zigbee map button in your left menu so you dont have to do anything in lovelace for it.

**Comment by joyka** [comment]
Splitting into 2 files would be awesome. The issue is not directly related to z2m map, there are so many custom cards available. I'm currently looking into how to incorporate https://github.com/bokub/rgb-light-card for instance.

And yeah I'm running hassio in docker on top of raspbian. I guess you refereed to https://github.com/rgruebel/ha_zigbee2mqtt_networkmap addon - I don't like the look and feel of it.

**Comment by dwainscheeren** [comment]
The next version will have a own file for your own resources! 😄 You can place them inside the file `dwains-theme/resources/custom_resources.yaml`
