### ISSUE TITLE
Graceful error handling for rooms without devices

### ISSUE THREAD

**Issue by Brausmith** [dwainscheeren/lovelace-dwains-theme#3]
I have a few rooms that have door/window sensors and/or a motion sensor, but nothing else.
These rooms throw a config error because there are no available cards for devices like lights, vacuums, etc.
![ha_dt_rooms](https://user-images.githubusercontent.com/3722950/74299104-cb0d3280-4d9f-11ea-98bf-1c8cc938300c.png)

**Comment by dwainscheeren** [comment]
Thanks this is indeed something what happens with only door, motion or windows inside a room. Will fix this in future update

**Comment by Brausmith** [comment]
Or, if a room has no cards, then maybe it doesn't need to be linked from the homepage into the room details?
Not sure if that is possible.

**Comment by dwainscheeren** [comment]
I'm not sure. I don't think a lot of people will have at least 1 light inside a room. For now you always can access a room page, but that error is gone in next version.

**Comment by dwainscheeren** [comment]
This will be fixed in 1.1.2
