### ISSUE TITLE
double "this room" graph on the climate card

### ISSUE THREAD

**Issue by mase60** [dwainscheeren/lovelace-dwains-theme#30]
it´s an issue introduced in v1.1.2. got it on all my climate-cards

[screenshot](http://tinyurl.com/smu4a2e)

**Comment by Holewijn** [comment]
It's indeed double, we only need the top 2 small cards.

**Comment by dwainscheeren** [comment]
It's not a bug it's a feature. I found the room graph too small so I placed a big one full screen below and seperated the temperature and humidity in it.

**Comment by dwainscheeren** [comment]
In the next version the extra big graphs will only show if you have a temperature AND humidity for a room set. So you can better look at those two in separate full width graphs.
