### ISSUE TITLE
[FR] Fan Entity

### ISSUE THREAD

**Issue by indy55** [dwainscheeren/lovelace-dwains-theme#31]
I saw a previous feature request has been closed, but wanted to open a new one in place.

Looking for the Fan entity (typically on/off with 3 speed settings) for ceiling fans

https://www.home-assistant.io/integrations/fan/

For additional information, a popular lovelace integration is "Lovelace Fan Control Entity Row"

Thanks for the great work!

**Comment by dwainscheeren** [comment]
#28 Continue here :)
