### ISSUE TITLE
[FR] Use special characters in room names

### ISSUE THREAD

**Issue by antonoal** [dwainscheeren/lovelace-dwains-theme#32]
When I added 4 rooms the homepage stopped displaying the rooms cards completely

**Comment by Benjy04** [comment]
then you have configured something wrong on room 4. I had the same issue.

**Comment by antonoal** [comment]
Just kept playing with it and discovered that it failed cause room 4 has had an apostrophe in the name. Not sure if it’s a bug or a limitation in general but happy to close the issue

**Comment by dwainscheeren** [comment]
Yeah you can't use any special characters in a room name only spaces. Need to look to fix option to add apostrophes.

**Comment by dwainscheeren** [comment]
Patched in 1.2.1
