### ISSUE TITLE
Vertical Slider for Cover not showing

### ISSUE THREAD

**Issue by MoMolap** [dwainscheeren/lovelace-dwains-theme#33]
My covers have `supported_features == 7 `.
They are showing in the cover page without the vertical slider, only with regular up and down buttons.

`cover-card.js` requires the cover to have `supported_features == 15`

```
  if(stateObj.attributes.supported_features == 15){
    //Cover has support for position (15)
```

**Comment by dwainscheeren** [comment]
Thanks need to look into this.

**Comment by dwainscheeren** [comment]
I added the option for if it has `supported_features == 7` to show the slider in 1.3.0
