### ISSUE TITLE
Add climate option for "Cool"

### ISSUE THREAD

**Issue by wjbeckett** [dwainscheeren/lovelace-dwains-theme#36]
The default lovelace thermostat card has the auto, cool, heat and power options. I notice that in the climate.yaml you only have auto, heat and power defined (cool is missing).

I have added the cool button in manually but I know the change will be overwritten with the next update. Just wondering if you can add the Cool button in there as well for the Thermostat card?

Thanks!

**Comment by dwainscheeren** [comment]
Hi,

I can't just add the cooling button because not every climate entity support cooling, also not every climate supports heat as that button is now always there. I'm looking into a way to show the buttons here that are available in your entity :)

**Comment by wjbeckett** [comment]
Ah yeah I understand.
Could do an if statement to populate the buttons based on what modes are defined in each climate device. By parsing the climate.<device_name>.attributes.hvac_modes maybe?

**Comment by dwainscheeren** [comment]
This is fixed in next version! :D

**Comment by wjbeckett** [comment]
> This is fixed in next version! :D

Amazing!
Thank you.
