### ISSUE TITLE
Input select 

### ISSUE THREAD

**Issue by jlucasgithub** [dwainscheeren/lovelace-dwains-theme#37]
After update to version 1.2.0  input_select doesn’t work like expected anymore
In previous version drop down menu appears and i could pick one of the options. But now it just triggers another option in the list. So it doesn't look like input_select anymore...

**Comment by dwainscheeren** [comment]
What if a single clicks opens the option list in popup, and touble tap loops thought the items? Or you want the dropdown directly in the button itself?

**Comment by jlucasgithub** [comment]
No need drop down menu. Popup sounds like good idea.

**Comment by dwainscheeren** [comment]
Fixed in 1.2.1, please let me know when its as you wanted or not :)
