### ISSUE TITLE
FR - 3rd window state 

### ISSUE THREAD

**Issue by jlucasgithub** [dwainscheeren/lovelace-dwains-theme#38]
Hi 

As far as i can tell at the moment only 2 states are acceptable for windows: on and off (open and close).
But modern windows has 3 states. Not sure if thats correct name, but its tilted windows

Please se picture: https://4e9dsh1squ2a41o9at4bz989-wpengine.netdna-ssl.com/wp-content/uploads/2016/10/Tilt-turn-windows-arrows-700x311.jpg

Is it possible to implement this?

**Comment by dwainscheeren** [comment]
Can you please post the states your sensor then has?

**Comment by jlucasgithub** [comment]
It is simply state: 0, 1, 2

**Comment by dwainscheeren** [comment]
What kind of sensors are that then? Never heard of them.

**Comment by jlucasgithub** [comment]
Sorry, i was not clear enough...

Here is how it works...
In each window you have 2 normall sensors *on the top and on the bottom). So to make it work in home assistant we just create template sensor like this:


        friendly_name: "Window"
        value_template: >-
             {% if is_state('binary_sensor.window_sensot_top', 'off') %}
                Close
             {% else %}
                {% if is_state('binary_sensor.window_sensot_bottom', 'off') %}
                    3rd state
                {% else %}
                    Open
                 {% endif %}
                {% endif %}

**Comment by dwainscheeren** [comment]
I added sort of support for this in 1.3.0 As soon as it's released let me know if it fixed your problem or not, otherwise re-open this issue, thanks.
