### ISSUE TITLE
Adding climate to a room removes the temp from card

### ISSUE THREAD

**Issue by Brausmith** [dwainscheeren/lovelace-dwains-theme#4]
When I create a room and add the temperature and humidity, the temperature value is displayed on the temperature card for the room.
But when I then add a climate device to the room, the temperature card goes blank.
![ha_dt_temp](https://user-images.githubusercontent.com/3722950/74299920-42dc5c80-4da2-11ea-8269-9908af050af1.png)

**Comment by dwainscheeren** [comment]
Can you please go to the Developer Tools inside HA and on the tab States open up a entity which is at your side a climate and post a screenshot of the state attributes data here please. So I can look into this.

**Comment by Brausmith** [comment]
No problem.

![ha_dt_climate](https://user-images.githubusercontent.com/3722950/74385255-4249d180-4e47-11ea-85bf-82ece076dc7f.png)

climate.bedroom
`hvac_modes: dry,heat_cool,heat,fan_only,cool,off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: quiet,low,medium_low,medium,medium_high,high,auto,strong
swing_modes: fixedTop,fixedMiddleTop,fixedMiddle,fixedMiddleBottom,fixedBottom,stopped
current_temperature: 24
temperature: 18
current_humidity: 90.5
fan_mode: medium
swing_mode: fixedMiddleTop
battery: null
friendly_name: Bedroom
supported_features: 41`

climate.media
`hvac_modes: dry,heat_cool,heat,fan_only,cool,off
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes: quiet,low,medium_low,medium,medium_high,high,auto,strong
swing_modes: fixedTop,fixedMiddleTop,fixedMiddle,fixedMiddleBottom,fixedBottom,stopped
current_temperature: 24.3
temperature: 25
current_humidity: 88.5
fan_mode: low
swing_mode: fixedMiddle
battery: null
friendly_name: Media Room
supported_features: 41`

**Comment by HunterArts** [comment]
Got the same issue.
I can get the temp back when i use the temp sensor from the climate device but i will use a extra sensor

**Comment by dwainscheeren** [comment]
Okay is this card empty on all states of the climate? Because there is a bug when the state is on 'heat' it doesnt show anything. When its on off it must show something. It will be fixed in next version

**Comment by dwainscheeren** [comment]
This will be fixed in 1.1.2. Please verify when this version is released if problem still exists re-open this issue. I also need to add some functionality for fans/cooling.
