### ISSUE TITLE
Light sliders not usable when light is off

### ISSUE THREAD

**Issue by jaburges** [dwainscheeren/lovelace-dwains-theme#41]
When the light is OFF, the sliders can not be used.

Meaning it is not possible to turn the brightness to anything other than 100%.

Let’s say I want to set the light to 50% - I have to switch the light ON (which is 100% full brightness) and then reduce it to 50%.

I should be able to drag the slider to 5% and it sends:
light.turn_on
brightness_pct: 5

**Comment by dwainscheeren** [comment]
This is not really a Dwains Theme bug but more of a bug of the way the light card works. I'm looking into making a own light card for this, but in the mean time I can't do anything about it. Sorry

**Comment by jaburges** [comment]
oh, apologies - i havent ever used a normal light card. I'll raise this in the polymer/lovelace HA repo.
did you want to keep this open to track? I'll add the issue info here
