### ISSUE TITLE
[FR] More than one climate control in each room

### ISSUE THREAD

**Issue by dkjsj** [dwainscheeren/lovelace-dwains-theme#45]
Consider adding group support for climate control? Eg. not "just" a climate entity in room.yaml but group entity for controlling all the climate control's with one command/click.

**Comment by dwainscheeren** [comment]
I'm not sure, but normally you have 1 climate entity inside 1 room?

**Comment by dkjsj** [comment]
> I'm not sure, but normally you have 1 climate entity inside 1 room?

For Thermostats - which is an climate control in HA - I have in one room 4 thermostats - one for each radiator valves - and hence 4 climate entities in one room.

**Comment by dwainscheeren** [comment]
Maybe use this? https://community.home-assistant.io/t/climate-group-custom-component-for-multiple-radiator-thermostats/103936 I recommend you to only have 1 climate in room, so combine those radiator valves in 1 control.

**Comment by dkjsj** [comment]
> Maybe use this? https://community.home-assistant.io/t/climate-group-custom-component-for-multiple-radiator-thermostats/103936 I recommend you to only have 1 climate in room, so combine those radiator valves in 1 control.

I wasn't aware of that custom-component. It works perfect with Dwains Theme :)

**Comment by dwainscheeren** [comment]
Nice :D
