### ISSUE TITLE
[FR] Home Information page improvements

### ISSUE THREAD

**Issue by Brausmith** [dwainscheeren/lovelace-dwains-theme#47]
There are two things which I think may improve the House Information (if they are possible):
1. The Activity list appears to be ordered by room name. Could this instead be ordered by entity name? I would prefer to rename my entities with the sensor domain first, e.g. Door, Motion, Window, etc.
2. Can the activity entities show their icons as per the entity icon for a clearer graphical representation?
![dwains-house-info](https://user-images.githubusercontent.com/3722950/75623838-0f029300-5bfa-11ea-87fc-025b75a163f6.png)

**Comment by dwainscheeren** [comment]
This will be fixed in 1.4
