### ISSUE TITLE
[FR] Now showing room name on the buttons

### ISSUE THREAD

**Issue by giosem** [dwainscheeren/lovelace-dwains-theme#5]
Hi Dwain,

how about including the option of not showing the room name on the buttons?

I think it will be nice just having the icon, if possible.

Thanks for your great work!

Bye
Giovanni

**Comment by mase60** [comment]
you could try `-name: " "` or do ALT+0160.

**Comment by dwainscheeren** [comment]
That wouldnt work because it uses the name for generating the url path's

**Comment by dwainscheeren** [comment]
This will be fixed in 1.1.2. You can then add `show_name: 'false'` inside a room object in `rooms.yaml`
