### ISSUE TITLE
[FR] Add locks to the rooms

### ISSUE THREAD

**Issue by martikainen87** [dwainscheeren/lovelace-dwains-theme#50]
Hi

It would be awesome to get locks added as a separate entity on a room, several of my rooms have doors that are accessible from the outside, and those doors have locks (duh :) ). Right now I've added them as "doors" which then displays as there is a door opened, but in reality it's the door lock that's open.

I figure they would be added just as a door/window in a room. 

Other stuff that would be nice to see, I'm guessing the code is pretty similar so I'm just adding it here in case anyone has the time to add it. 

- Smoke Alarms
- Water sensors
- custom sensor? posibility to add one/several custom sensors in the form of a binary_sensors, which are editable with info (name/icon).

Thanks for an awesome theme Dwain!

**Comment by dwainscheeren** [comment]
I'm actually working on adding support for 'locks' inside a room. It will create a seperate button for it inside the room with an own page. So that's something that is deferentially coming in a next update.

Regarding your other sensors you can use `more_entities` or `page_entities` for this inside a room. It will add these sensors inside a popup in the room or if you use `page_entities` they will be directly visible on the room page itself.

**Comment by martikainen87** [comment]
Oh thats awesome!  Looking forward to it! 

And regarding the other sensors, it would be nice to show the status on the homepage, just for visibility that something has happen. But since it's smoke/water alarm I'm talking about I already have separate triggers for that, so not that important :)  

Maybe a custom sensor (icon on a roombutton on the homepage) for people who would like to show something more, like a dishwasher running, the heater for a car etc. I had this on my own theme before I found this and found it very useful for quick information about the status of the home.

**Comment by dwainscheeren** [comment]
Yeah that's related to #25 

For smoke/water alarm etc I agree with you, people asked me to make them visibible inside a room if they are triggered. But when my smoke alarm should trigger I want a direct notification on my phone and then i'm in big trouble. I'm not going to open the HA app then in all patience 😆 

I'm working on a function to disable some notifications on the homepage with pushing them to it.

**Comment by martikainen87** [comment]
Sounds great, I'm closing this FR since everything is already under control! 

Thanks a lot for the quick answers and all the effort!

**Comment by dwainscheeren** [comment]
No problem, thank you

**Comment by dwainscheeren** [comment]
Locks will be available in 1.3.0
