### ISSUE TITLE
[BUG] Font in current entities screen invisible when using dark theme

### ISSUE THREAD

**Issue by cmdekleijn** [dwainscheeren/lovelace-dwains-theme#52]
Minor issue really, but this requires me to switch themes when I need to look some entities up.

Issue is that when using the Dwains Dark Theme, the font color makes the entity text invisible in the 'Developer tools' / 'States' / 'Current entities' screen.

See attached screens for clarification.

![screen1](https://user-images.githubusercontent.com/5500353/75858097-c3b5d380-5df7-11ea-9621-2f7a7c464ada.png)
![screen2](https://user-images.githubusercontent.com/5500353/75858095-c31d3d00-5df7-11ea-923b-10400828407b.png)

**Comment by dwainscheeren** [comment]
I know this is a bug I cant fix right now. It's because HA uses the font color `var(--primary-color)` that is set to dark grey/black to give the HA iOS app and dark notch. If I set it to a white color so the text is better readable the iOS app notch becomes white too.

**Comment by dwainscheeren** [comment]
Seems like this if fixed in next iOS app release :D

**Comment by cmdekleijn** [comment]
Ah, so they saw my bug report ;)

**Comment by dwainscheeren** [comment]
No idea :P where you put it? I did this: https://github.com/home-assistant/home-assistant-iOS/issues/561

**Comment by cmdekleijn** [comment]
No, I meant *this* bug report... It was a bad attempt at humor :)

**Comment by dwainscheeren** [comment]
Ah haha I thought you openend one in the iOS app github :P haha

**Comment by dwainscheeren** [comment]
As soon as HA releases the new iOS app this is fixed, for now I can not do anything about it so I will close this issue.
