### ISSUE TITLE
[Wish list] Add already present Lovelace Custom Cards

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#54]
Hi all, I don't know if it is a good idea to post each feature request. Good would be to bundle this in one request. I also think that it might be easier to implement already present cards into this theme. I made a list with custom:cards I'd like to see in this theme.

[Flex Card](https://github.com/custom-cards/flex-table-card)

**Comment by PostSven** [comment]
You can use all custom cards you want in the addons, what are you missing?

**Comment by thundergreen** [comment]
Could you give me a hint how? :P I would like adding custom cards into this theme.

**Comment by PostSven** [comment]
it's all in the documentation
https://dwainscheeren.github.io/lovelace-dwains-theme/addons/more_page.html

you can use the page.yaml as a view and place everything you want there.
