### ISSUE TITLE
[Pull request] Translation to PT-BR

### ISSUE THREAD

**Issue by clfregis** [dwainscheeren/lovelace-dwains-theme#55]
Hello, I loved this theme and I would like to contribute translating it to Brazilian Portuguese.
My question is, in what occasion we would have a "plant problem"?
I need to know the context in order to translate it correctly. I never had plants on my automation =/

P.S.: In Home Assistant there are some words that are translated automatically depending on the language chosen by user on Profile page. For instance, "Home" state of person is automatically translated into "Em casa" when I choose Brazilian Portuguese as language. Is it possible to do this in this theme?

**Comment by dwainscheeren** [comment]
Plant has only 2 status if all sensors are good the plant is okay otherwise it has a plant problem.

I wil look into making the translations more universe.

**Comment by clfregis** [comment]
Nice, well I did the translation and tested this week. It's working pretty fine.
[pt-br.yaml.txt](https://github.com/dwainscheeren/lovelace-dwains-theme/files/4346266/pt-br.yaml.txt)
