### ISSUE TITLE
Can't open drawer when Android gesture navigation is on

### ISSUE THREAD

**Issue by sanyatuning** [dwainscheeren/lovelace-dwains-theme#57]
More info:
https://www.androidcentral.com/android-q-back-gesture-going-be-pain-until-developers-update-apps

**Comment by dwainscheeren** [comment]
And how is this related to my theme?

**Comment by sanyatuning** [comment]
I think we need a button or something which can open it.

**Comment by dwainscheeren** [comment]
In 1.3.0 you can swipe from left in the Android app to reveal the HA app sidemenu :)
