### ISSUE TITLE
[FR] single button to turn on/off all lights

### ISSUE THREAD

**Issue by mase60** [dwainscheeren/lovelace-dwains-theme#6]
since i don´t use an alarm, but i often toggle all my active lights to off it would be awesome to have the option to replace the alarm-lock-icon to a light toggle button.

**Comment by derelict** [comment]
i would suggest to NOT replace the alarm button (i also use the alarm) but rather add a second button and/or turn all lights off/on by double tapping the header or something like that.

**Comment by xPhantomNL** [comment]
I would love an option to toggle all the lights as well. I think a good location for such a button would be on the 'All lights' page, on the right side of the header.

**Comment by dwainscheeren** [comment]
I'm working on a toggle for this on the all lights page. Update you when its ready.

**Comment by dwainscheeren** [comment]
It's almost done :D Hope it works good it was a lot of work to create a simple button like this!

**Comment by mase60** [comment]
sounds good. 
i just did a room named „flat“ with all lights, covers and heaters in it.

**Comment by dwainscheeren** [comment]
Added in version 1.2.0
