### ISSUE TITLE
[FR] Plant overview integration

### ISSUE THREAD

**Issue by deku-m** [dwainscheeren/lovelace-dwains-theme#62]
Hi Dwains,

**First of all awesome work on your theme! Thanks.**

But i`ve got a question regarding the plant integration in rooms. Is it possible to extend it with more info when you click on it. The miflora i use has the card ability.

So when clicking in the room on plants you will see which flowers has a problem or is ok.
But when you click on them you get the default hass view (screenshot 1).  Same as you do for temperature. When clicking on the temp you will proceed to overview page.

See screenshots for info regarding plants.

**Screenshot 1:**
https://imgur.com/8SJp4xh

**Screenshot 2:**
https://imgur.com/tBgjxs9

**Comment by dwainscheeren** [comment]
In 1.4.0 you can make own popup for entities, so you can make this yourself. For now I can't integrate this as default because not every plant sensor works with the miflora card

**Comment by deku-m** [comment]
I think this can be closed as it is already provided through the addon-section github.
Thanks  for the contribution.
