### ISSUE TITLE
Navigation moves several pixels except homepage

### ISSUE THREAD

**Issue by broesie** [dwainscheeren/lovelace-dwains-theme#63]
Navigation moves several pixels if you click on other tabs than home.
I tested it with the android app, also with chrome on phone.

With app: Homepage is ok
![Screenshot_20200405-114103](https://user-images.githubusercontent.com/21012345/78471658-3e457c00-7733-11ea-840d-2ca258ec5494.png)

With app: jumping to another tab, navigation moves several pixels upwards.
![Screenshot_20200405-114054](https://user-images.githubusercontent.com/21012345/78471684-69c86680-7733-11ea-9237-cd3f93b004cb.png)

In chrome on phone: jumping to another tab, navigation moves several pixels upwards.
![Screenshot_20200405-114140](https://user-images.githubusercontent.com/21012345/78471695-7b117300-7733-11ea-8dba-fabc5100bcee.png)

**Comment by broesie** [comment]
![pixel](https://user-images.githubusercontent.com/21012345/78471963-89f92500-7735-11ea-88ee-d69b3036f6ed.png)

**Comment by dwainscheeren** [comment]
This should be fixed in 1.4, please re-open this issue if not.
