### ISSUE TITLE
[FR] Add CSS styling to the theme

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#66]
MIght be handsome having some css style codes for individual tastes? Some maybe basic functions like: Background image / widget Style etc. I know I can make this my own but will be deleted after upgrading .. For this an external config might be helpful here

**Comment by dwainscheeren** [comment]
Maybe I will add this in the feature, for now it's the base of my theme, people who don' like the style can use an other theme.
