### ISSUE TITLE
[FR] update custom:mini-graph-card to match the theme

### ISSUE THREAD

**Issue by mase60** [dwainscheeren/lovelace-dwains-theme#67]
adding these two values to match the look of the theme would be nice imo:

`line_color: 'dwains-theme-accent'`

```
style: |
  ha-card {
    background-color: var(--dwains-theme-primary);
  }
```

left is with values, right the way it looks now
![image0](https://user-images.githubusercontent.com/5972205/78695685-b3b17800-78fe-11ea-9f1d-b5f2dbe937ce.png)

**Comment by Baumtreter** [comment]
Also "secondary-axis" would be great!

**Comment by dwainscheeren** [comment]
The custom mini graph card is fully deprecated in version 1.4, I will move to the HA default graph so it's styled then that way :)
