### ISSUE TITLE
[FR] bring back "old" Alarm Panel Card

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#68]
native hass alarm cars is a way to .... ugly und small for touchscreens and looks not really dashboardy :) Please bring back the alarm panel back in 1.2

**Comment by iamandymcinnes** [comment]
Yeah can we get some of the nice lovelace cards interlaced with the nice dashboardy stuff you have created? E.g. the alarm, the media player, maybe even the weather card.

**Comment by dwainscheeren** [comment]
This will be back in 1.4.0
