### ISSUE TITLE
[FR] Link OpenDoors/Windows to a page

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#70]
That's a real nice feature to see that x doors/windows are still open. But to know which ones we need to make an extra step into house information to see which doors/windows are open.

Can we make a like by clicking on open windows/doors in the header to the site in house information where all open doors/windows are shown?

Also the fitting of those sensors is let's say.. not 100% 

![image](https://user-images.githubusercontent.com/13320319/78713670-ecf7e100-791a-11ea-916f-b94c7bf5d221.png)
Unnesessary space down a page is used .. maybe they can be fit also horizontally?

**Comment by flonair** [comment]
+1 
I also think it would be better if you could click on "1 window open" to see which one is open instead of "house information". It wouldn't be faster, but much more intuitive.

**Comment by dwainscheeren** [comment]
This is fixed in 1.4! 👍
