### ISSUE TITLE
[BUG] All Lights page strange fitting

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#71]
![image](https://user-images.githubusercontent.com/13320319/78713812-1d3f7f80-791b-11ea-9c0f-437d58b69334.png)

I think there's a lot of space lost on this page.. maybe a better fiiting would help here?

**Comment by Tosko4** [comment]
It’s not really a bug though. It works as designed. Nonetheless, could be prettier indeed. Maybe change it from bug to Request [REQ]

**Comment by dwainscheeren** [comment]
This is not a bug. It works like this. With the flexbox card I cant stack them in the empty space of each other. I had that before with layout-card but personally I think this way it's also better because it is a lot cleaner and more organized.

**Comment by thundergreen** [comment]
The "bug" here is more like I lose a lot of space :/

**Comment by dwainscheeren** [comment]
It all fits nicely on your screen

**Comment by Tosko4** [comment]
@thundergreen i see this issue going nowhere. Maybe you can help if you have any suggestions on how to display it. Given the fact of the technical css limitations, how would you rather see it? 

As dwain mentioned before; it is not possible with the way this is coded

**Comment by thundergreen** [comment]
closed :)
