### ISSUE TITLE
[FR] Add groups to scenes

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#72]
It is nice having scenes. Maybe it is possible to add groups? Header or whatelse to "group" those scenes like into Lights / Rooms / Usecases etc or whatever?

![image](https://user-images.githubusercontent.com/13320319/78713978-5bd53a00-791b-11ea-9ebb-0bec6c17308f.png)

**Comment by dwainscheeren** [comment]
I personally don't see an advantage for this because people don't have much scenes, maybe if a lot of people want this (who wants this) I will take a look at it, for now I will close this 😈

**Comment by iroQuai** [comment]
this would be wonderful! Every room has different scenes (mostly depending on time of day)
but since i'm the first one in 1,5yrs to comment this, its probably not a feature that is wanted a lot :)
