### ISSUE TITLE
[BUG] icons for battery levels not showing in each cases (very low battery)

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#73]
I've some battery powered devises with a very low level of battery. Unfortunately there's no icon shown:

![image](https://user-images.githubusercontent.com/13320319/78714085-8b844200-791b-11ea-98a3-0d61295f7b64.png)

**Comment by dwainscheeren** [comment]
This will be fixed in 1.4
