### ISSUE TITLE
[FR] Add new native Lovelace media Player card

### ISSUE THREAD

**Issue by thundergreen** [dwainscheeren/lovelace-dwains-theme#74]
I think instead of having button cards it would be niceer to replace them directly with something more beautiful like native media PLayer card:

![image](https://user-images.githubusercontent.com/13320319/78714215-c5554880-791b-11ea-9b0a-a3265132b645.png)

**Comment by Tosko4** [comment]
I agree. I think these kinds of cards will only compliment the Dwain theme.

**Comment by thundergreen** [comment]
Yeah!

**Comment by dwainscheeren** [comment]
This is done in version 1.4.
