### ISSUE TITLE
[FR] Norwegian translation

### ISSUE THREAD

**Issue by lundig** [dwainscheeren/lovelace-dwains-theme#79]
Is it possible to add Norwegian language?
I can help if you need help with translation  :-)

**Comment by Tosko4** [comment]
Of course. Just add a language file here and do a Pull Request to dwains theme. 

https://github.com/dwainscheeren/lovelace-dwains-theme/tree/1.3/dwains-theme/translations

**Comment by lundig** [comment]
Done :)
