### ISSUE TITLE
[FR] Add choice to buttons for switch/more-info

### ISSUE THREAD

**Issue by pservais** [dwainscheeren/lovelace-dwains-theme#8]
It would be nice to choose the action when single-click a button, more-info (default now) of switch entity. We use input_booleans for housemodes and the wife dislikes if she has to make multiple actions to set a housemode

**Comment by dwainscheeren** [comment]
Can you explain this more for me what you exactly mean? :)

**Comment by MrHasse** [comment]
I think he wants the "double tap action" on entites to be reversed. So when you press an entity it activates/deactivates and double tap/hold down displays "more-info".

**Comment by pservais** [comment]
Sorry, haven't seen the question earlier.
Like what MrHasse says, or perhaps a variable which we can set:
single_tap: more-info
double_tap: toggle

**Comment by dwainscheeren** [comment]
Need to look into this but it is maybe possible.

**Comment by crsarnelli** [comment]
Dwain,

Thank you so much for your time and effort! I started today and I really like it so far.

single tap for toggling will help me pass the wife effect.

Thanks you!

**Comment by dwainscheeren** [comment]
I will make it more consistent in 1.4.0 and configurable option for this would be a lot of work, maybe sometime in the future.
