### ISSUE TITLE
Custom element doesn't exist: dwains-flexbox-card.

### ISSUE THREAD

**Issue by frznfngrs** [dwainscheeren/lovelace-dwains-theme#80]
I have tried installing 2 separate times from my working setup.  I receive this error on the dwains theme dashboard

type: 'custom:dwains-flexbox-card'
cards:
  - type: markdown
    item_classes: col-xs-8
    style: |
      ha-card {
        background: transparent;
        box-shadow: none;
        margin-top: -4px;
      }
      ha-markdown {
        padding-top: 0px !important;
        padding-bottom: 3px !important;
        padding-left: 11px !important;
      }
      ha-card a {
        color: var(--dwains-theme-header-text) !important;
      }
      ha-card p {
        margin-bottom: 0px;
      }
      ha-card h1 {
        color: var(--dwains-theme-header-text);
        font-size: 1.5em;
        
        margin: 10px 0 0 0;
        
      }
      ha-card h3 {
        font-size: 13px;
        font-weight: normal;
        color: var(--dwains-theme-header-text);
        
        margin: 0;
        
      }
    content: |

      <h3></h3>
      <h1>All lights</h1>
  - type: vertical-stack
    item_classes: col-xs-4
    cards:
      - type: 'custom:button-card'
        template: lights_header_all_lights_toggle
        icon: 'fas:lightbulb'
        tap_action:
          haptic: light
          action: call-service
          service: homeassistant.turn_off
          service_data:
            entity_id:
              - switch.z_wave_products_inc_unknown_type_4447_id_3033_switch
        styles:
          card:
            - display: |
                [[[
                  var onLights = 0;

                  
                    //Do some things for the lights
                    
                      
                      //This room has only 1 light
                        if(states['switch.z_wave_products_inc_unknown_type_4447_id_3033_switch'] && states['switch.z_wave_products_inc_unknown_type_4447_id_3033_switch'].state == 'on') {
                          onLights++;
                        }
                      
                    
                  
                    //Do some things for the lights
                    
                  
                  if(onLights == 0){
                    return 'none';
                  } else {
                    return 'block';
                  }
                ]]]
      - type: 'custom:button-card'
        template: lights_header_all_lights_toggle
        icon: 'far:lightbulb'
        tap_action:
          haptic: light
          action: call-service
          service: homeassistant.turn_on
          service_data:
            entity_id:
              - switch.z_wave_products_inc_unknown_type_4447_id_3033_switch
        styles:
          card:
            - padding: 0px 0 0 0
            - display: |-
                [[[
                  var onLights = 0;

                  
                    //Do some things for the lights
                    
                      
                      //This room has only 1 light
                        if(states['switch.z_wave_products_inc_unknown_type_4447_id_3033_switch'] && states['switch.z_wave_products_inc_unknown_type_4447_id_3033_switch'].state == 'on') {
                          onLights++;
                        }
                      
                    
                  
                    //Do some things for the lights
                    
                  
                  if(onLights == 0){
                    return 'block';
                  } else {
                    return 'none';
                  }
                ]]]

**Comment by dwainscheeren** [comment]
Please join my Discord server for support on this https://discord.gg/7yt64uX

**Comment by dwainscheeren** [comment]
Also c heck
