### ISSUE TITLE
Top back button is hard to hit on some phones

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#86]
I feel I figured it mostly out, you click more to the right of the left arrow than trying to click on the right arrow, but it took me a couple of days to find the sweet spot and was hard to teach the wife.  It was easier on some phones.  I would say make the click area larger and maybe make it a larger button than just the left arrow to make it more clear, the whole word Back in a square, something.

**Comment by Tosko4** [comment]
+1

**Comment by Baumtreter** [comment]
Can confirm that. Ipads are affected too

**Comment by dwainscheeren** [comment]
This is fixed in 1.4 I made the back button larger.
