### ISSUE TITLE
[FR] Other brightness options than double click for a light

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#87]
Can you add something to the light card, if a light and not a switch, maybe and "..." to the far right of the card, or something that loads the brightness settings, double clicking was not natural and I had to go read to figure it out and sometimes if you don't do it right, you end up turning the light on and off

**Comment by dwainscheeren** [comment]
In 1.4 it will be more standard, read the 1.4 changelog for more info (when it's released)
