### ISSUE TITLE
[FR] Clicking on a lock should toggle, not load entity details

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#88]
I saw the other FR for a lock card, but something simple could be clicking a lock toggles the lock, so unlock or lock, and if you double click or click the "..." at the far right, you can pull up the entity details if needed, might be easier while a lock card is worked on

**Comment by Baumtreter** [comment]
+1

**Comment by dwainscheeren** [comment]
Adjusted this in 1.4 :)
