### ISSUE TITLE
Inactive motion does not show an icon

### ISSUE THREAD

**Issue by Brausmith** [dwainscheeren/lovelace-dwains-theme#9]
When a room detects motion it correctly shows the active motion icon. When there is no motion then is shows no icon at all, i.e. it is blank.
This is occurring on both the desktop and mobile app.
![ha_dt_motionicon](https://user-images.githubusercontent.com/3722950/74385138-f303a100-4e46-11ea-86c7-a36f1bc488fe.png)

**Comment by dwainscheeren** [comment]
Thanks. I used a FA Pro icon here, forgot to change it to a Free icon. On the next version this is fixed.
