### ISSUE TITLE
Devices page issues showing rooms

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#90]
If you are on the main page, and click on Devices, and then go into Locks, or Temperature, etc...  It will switch back to show Rooms page for a second before it loads the screen you are trying to go too.  When you hit back, it does go back to the Devices section and work...

This also happens if you are on the Devices page and click something in the footer, like scenes or cameras, it will flicker back to Rooms and then go to the other section or page

**Comment by dwainscheeren** [comment]
This will be fixed in 1.4
