### ISSUE TITLE
[FR] Going to Devices and then Lights doesn't follow UX flow

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#91]
If you go to Devices and then click Lights, it goes to the Lights section in the footer, which is different than every other item in Devices, which goes to a section with a back button in the top with a header.  If you go to Lights from Devices can you add the Back button in the header.  It can still not have the back button if you click to get there from the footer.

**Comment by dwainscheeren** [comment]
This will be fixed in 1.4
