### ISSUE TITLE
Error, "Custom element doesn't exist: dwains-flexbox-card"

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#93]
I get this error at times, not often, but usually a refresh or two makes it go away, maybe close HA and open it again.

https://photos.app.goo.gl/HKMQCAGVZ6cHcT1p8

**Comment by mike391** [comment]
I just started getting this intermittently as well on 1.3.1

**Comment by deku-m** [comment]
I had this error to, maybe its in 108.x version. But it goes away when reloaded.

**Comment by DamianosS** [comment]
I had this error as well and the solution for me was updating HACS to the most recent version.

**Comment by davidkmcgowan** [comment]
I was on .23.X I just upgraded to .24, I will see if it happens again, if not I can close it

**Comment by davidkmcgowan** [comment]
So far it has not happened again, maybe just a HACS issue, I will give it a couple of days and then we can close this and should tell everyone to be on the latest version of HACS

**Comment by davidkmcgowan** [comment]
It happened again this morning, on the latest version of HACS.  I switched to Theme auto mode, was in light only, and this morning when I loaded, it was dark, and then it went to auto flip to light, it flashed the red error screen, then loaded the light theme

**Comment by chansters** [comment]
I just installed this theme today and it's awesome ! But I'm also getting this error message. I'm on the latest HACS (0.24.3) and Home Assistant 0.109.  Refreshing does make it goes away.

**Comment by dwainscheeren** [comment]
Still got this problem after HA reboot?

**Comment by chansters** [comment]
No, this message went away after the first couple of times of rebooting.  I haven’t seen it for the past 24 hours now.

**Comment by davidkmcgowan** [comment]
I had a good run, but saw it again today.  A refresh always fixes it for me, but still happens for sure, I'm on 109.5 and HACS fully updated as well

**Comment by jaedesignz** [comment]
any one resolved this issue, i'm also getting the same error even with the latest HA version 0.110.1

**Comment by chansters** [comment]
> any one resolved this issue, i'm also getting the same error with HA v0.109.6

I am seeing this occasionally but a refresh clears it up.

**Comment by jaedesignz** [comment]
> > any one resolved this issue, i'm also getting the same error with HA v0.109.6
> 
> I am seeing this occasionally but a refresh clears it up.

tried refreshing, restoring, wiping and fresh install and still the same error :(

**Comment by dwainscheeren** [comment]
And a browser cache renew?

**Comment by jaedesignz** [comment]
> And a browser cache renew?

yes also a cache renew & hard reload

**Comment by jaedesignz** [comment]
Ok, so i figured out what was the problem. My current DNS was blocking some of your online js that was needed. It was being detecting it as an AD which was blocking it. So i whitelisted those specific js files and got it to work.

**Comment by dwainscheeren** [comment]
I think its the same problems others are having then. Its loads some code from https://unpkg.com. Please check if that url is not blocked.

**Comment by jaedesignz** [comment]
> I think its the same problems others are having then. Its loads some code from https://unpkg.com. Please check if that url is not blocked.

yes that's exactly the url I had to whitelist in order to for the theme to load properly so far 24hr and still working. BTW great job on the theme.

**Comment by dwainscheeren** [comment]
Thanks, I think this is the solution so I will close this for now.

**Comment by corvis** [comment]
Hi @dwainscheeren, thank you for your work! 

Are there any plans to get rid of external dependencies? The fact it loads some code from https://unpkg.com makes system absolutely nonfunctional in case of ISP failure or electricity failure. It would be great to make it work offline and also offline bundle should decrease initial loading time.
