### ISSUE TITLE
[FR] Add to the left of Home icon in the top the 3 bars to pull out sidebar

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#95]
To swipe the bar bar is really hard.  I still need to get to things like Map, Logbook, History, and HACS.  You gave a nice way in House data to get to Config and Developer tools, but can't get to the others except going to the far right More footer item, then House Data, then Config, then clicking the top 3 bars

**Comment by dwainscheeren** [comment]
You can swipe from left to reveal the sidebar, its default in the HA app?
