### ISSUE TITLE
[FR] Add map, logbook, and history to More section

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#96]
It would be nice to get to map, logbook, and history from the more section, even better if a way to iframe it or something so the theme header could stay with a back button

**Comment by Tosko4** [comment]
no need to iframe it all, easy to create a card for this. nice one

**Comment by dwainscheeren** [comment]
Personally don't see the direct advantage on this. Those are directly available in the sidemenu, which is available on all devices?

**Comment by Tosko4** [comment]
It’s not a must-have, it’s rather a nice to have. And I agree, maybe not something to be spending too much time on. When integrating, means you’ll have to maintain it.

Maybe someone could write an addon for it, but should not be in main integration. @dwainscheeren

**Comment by davidkmcgowan** [comment]
also fine if you close, and I had another FR for getting easier access to side bar, if that was there, then you can access it all pretty easy, right now you have to go to More, then House Data, then Config, then click side bar, or get lucky on a swipe.  This was about making your Theme more of a complete Dashboard, but I could understand this being super low priority or never in your mind, close away if you think

**Comment by dwainscheeren** [comment]
When its good you can just swipe from left and it opens the sidebar.

**Comment by dwainscheeren** [comment]
Checked?

**Comment by davidkmcgowan** [comment]
I'm on the Pixel 4 and use gestures, so swiping left or right will do back/forward for the browser, so I guess it's just a Pixel 4 gesture issue
