### ISSUE TITLE
[FR] Add header and back button for config and developer tools

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#97]
In the More, House Data, Config and Developer Tools, anyway to iframe that and keep the theme header with a back button or something else to make the UX flow?

**Comment by dwainscheeren** [comment]
Not see any advantage for this, this is outside my theme and standard HA (settings) stuff. Including them inside an iframe will also cause a lot of problems (technical viewed)
