### ISSUE TITLE
[FR] Alarm in top right pulls up just the entity, can it go to alarm card

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#98]
Would be nice to see the alarm card and not the entity, this could be a duplicate FR from the one about using the old lovelace alarm card, if it's the same thing just close this

**Comment by Tosko4** [comment]
please close this issue @davidkmcgowan or @dwainscheeren , there is already a request for this:

https://github.com/dwainscheeren/lovelace-dwains-theme/issues/68
