### ISSUE TITLE
[FR] HA notifications showing up in theme notifications

### ISSUE THREAD

**Issue by davidkmcgowan** [dwainscheeren/lovelace-dwains-theme#99]
There is the HA notifications section, shows new discovered devices, failed login attempts, etc...  can you intercept those and make them show up in the theme notifications, and be dismissed, and then have them also get removed and dismissed from the HA notifications section

**Comment by dwainscheeren** [comment]
This would not be possible unfortunately. You can use Dwains Theme Notifications but you have to make them yourself from an automation for example. I personally don't like to combine this with the HA notifications.
